### ISSUE TITLE
Setup Files Absent

### ISSUE THREAD

**Issue by unworld11** [facebookresearch/maze_navigation_MLMU#1]
the readme asks us to run the commans 
`pip install -e .`
but there is no setup.py or .toml file so
we recieve the error
`ERROR: file:///xx/xx/xx/maze_navigation_MLMU does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by niklasnolte** [comment]
sorry about the artifact. I tried just now and i could run things without installing the package. please check whether skipping the step works. I also forgot some dependencies in the pip list, please refer to the updated readme.

LMK if anything else goes wrong.

**Comment by unworld11** [comment]
it does work, without that step.
just needed you to update it, thanks.
great paper, i am trying to build up on it.
would love to have a chat

**Comment by niklasnolte** [comment]
thanks! sure, shoot me an email and we can schedule a chat.
